# Generated by Django 5.2.6 on 2025-09-28 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_coursesection_is_general_subjectgroup_external_id'),
        ('schools', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrosoftGraphConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=255, unique=True)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Microsoft Graph Configuration',
                'verbose_name_plural': 'Microsoft Graph Configurations',
            },
        ),
        migrations.CreateModel(
            name='SchoolMicrosoftAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microsoft_email', models.EmailField(help_text='Microsoft account email used for this school', max_length=254)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_type', models.CharField(default='Bearer', max_length=50)),
                ('expires_at', models.DateTimeField()),
                ('scope', models.TextField(help_text='Comma-separated list of granted scopes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_microsoft_accounts', to=settings.AUTH_USER_MODEL)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='microsoft_account', to='schools.school')),
            ],
            options={
                'verbose_name': 'School Microsoft Account',
                'verbose_name_plural': 'School Microsoft Accounts',
            },
        ),
        migrations.CreateModel(
            name='OnlineMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_title', models.CharField(max_length=255)),
                ('meeting_description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('microsoft_meeting_id', models.CharField(max_length=255, unique=True)),
                ('join_url', models.URLField()),
                ('meeting_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_online_meetings', to=settings.AUTH_USER_MODEL)),
                ('subject_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_meetings', to='courses.subjectgroup')),
                ('school_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_meetings', to='microsoft_graph.schoolmicrosoftaccount')),
            ],
            options={
                'verbose_name': 'Online Meeting',
                'verbose_name_plural': 'Online Meetings',
                'ordering': ['-created_at'],
            },
        ),
    ]
