# Generated by Django 5.2.6 on 2025-09-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft_graph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microsoftgraphconfig',
            name='tenant_id',
            field=models.CharField(blank=True, help_text='Leave empty for multi-tenant (common) apps', max_length=255, null=True),
        ),
    ]
