# Generated by Django 5.2.6 on 2025-09-28 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursesection_is_general_subjectgroup_external_id'),
        ('microsoft_graph', '0002_alter_microsoftgraphconfig_tenant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinemeeting',
            name='subject_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_meeting', to='courses.subjectgroup'),
        ),
    ]
