# Generated by Django 5.2.6 on 2025-10-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresettoken',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='passwordresettoken',
            unique_together={('token', 'used')},
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['token'], name='users_passw_token_b56ca3_idx'),
        ),
    ]
