# Generated by Django 5.2.6 on 2025-12-19 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_passwordresettoken_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="children",
            field=models.ManyToManyField(
                blank=True,
                help_text="For parent accounts: linked student children.",
                limit_choices_to={"role": "student"},
                related_name="parents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Admin"),
                    ("schooladmin", "School Admin"),
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                    ("parent", "Parent"),
                ],
                default="student",
                max_length=32,
            ),
        ),
    ]
