# Generated by Django 5.2.6 on 2026-01-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_children_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_active",
            field=models.DateTimeField(
                blank=True, help_text="Last time user was active", null=True
            ),
        ),
    ]
