# Generated by Django 5.2.6 on 2026-01-26 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0013_answer_is_resolved"),
        ("forum", "0004_postreaction"),
        ("learning", "0011_assignment_template_due_time_and_more"),
        ("users", "0004_user_last_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("new_assignment", "New Assignment"),
                            ("assignment_graded", "Assignment Graded"),
                            ("new_test", "New Test"),
                            ("test_available", "Test Available"),
                            ("test_graded", "Test Graded"),
                            ("forum_reply", "Forum Reply"),
                            ("forum_mention", "Forum Mention"),
                            ("forum_resolved", "Forum Resolved"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField(blank=True)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="learning.assignment",
                    ),
                ),
                (
                    "related_forum_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="forum.forumpost",
                    ),
                ),
                (
                    "related_forum_thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="forum.forumthread",
                    ),
                ),
                (
                    "related_test",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="assessments.test",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications_triggered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="users_notif_user_id_c37f16_idx",
                    ),
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="users_notif_user_id_f3f50a_idx",
                    ),
                ],
            },
        ),
    ]
