# Generated by Django 5.2.6 on 2026-01-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("new_assignment", "New Assignment"),
                    ("assignment_graded", "Assignment Graded"),
                    ("new_test", "New Test"),
                    ("test_available", "Test Available"),
                    ("test_graded", "Test Graded"),
                    ("forum_question", "Forum Question"),
                    ("forum_reply", "Forum Reply"),
                    ("forum_mention", "Forum Mention"),
                    ("forum_resolved", "Forum Resolved"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=32,
            ),
        ),
    ]
