# Generated by Django 5.2.6 on 2026-02-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='iin',
            field=models.CharField(blank=True, help_text='12-digit Individual Identification Number', max_length=12, null=True, unique=True),
        ),
    ]
