# Generated by Django 5.2.6 on 2025-09-18 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
        ('courses', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='course',
        ),
        migrations.AddField(
            model_name='test',
            name='course_section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='courses.coursesection'),
            preserve_default=False,
        ),
    ]
