# Generated by Django 5.2.6 on 2025-09-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_rename_match_json_answer_auto_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
