# Generated by Django 5.2.6 on 2025-10-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_alter_test_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='key_words',
            field=models.TextField(blank=True, help_text='Comma-separated keywords for automatic grading of open questions', null=True),
        ),
    ]
