# Generated by Django 5.2.6 on 2025-10-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_question_key_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='time_limit_minutes',
        ),
        migrations.AddField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Test end date and time', null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Test start date and time', null=True),
        ),
    ]
