# Generated by Django 5.2.6 on 2025-10-08 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_remove_test_time_limit_minutes_test_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='scheduled_at',
        ),
    ]
