# Generated by Django 5.2.6 on 2025-12-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0008_remove_scheduled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="time_limit_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Time limit in minutes for completing the test once started. If not set, there is no per-attempt time limit.",
                null=True,
            ),
        ),
    ]
