# Generated by Django 5.2.6 on 2026-01-23 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0009_test_time_limit_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="is_unlinked_from_template",
            field=models.BooleanField(
                default=False,
                help_text="If true, this test is no longer auto-synced from its template.",
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="template_test",
            field=models.ForeignKey(
                blank=True,
                help_text="Template test this test was cloned from (if any).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_tests",
                to="assessments.test",
            ),
        ),
    ]
