# Generated by Django 5.2.6 on 2026-01-23 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0010_test_is_unlinked_from_template_test_template_test"),
        ("courses", "0008_add_language_to_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="course_section",
            field=models.ForeignKey(
                blank=True,
                help_text="Course section for this test. Can be null for template tests not tied to a specific section.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="courses.coursesection",
            ),
        ),
    ]
