# Generated by Django 5.2.6 on 2026-01-24 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0011_alter_test_course_section"),
        ("courses", "0008_add_language_to_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Course this test belongs to. Set for template tests, null for regular tests tied to sections.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="courses.course",
            ),
        ),
    ]
