# Generated by Django 5.2.6 on 2026-01-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0012_test_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="is_resolved",
            field=models.BooleanField(
                default=False,
                help_text="Whether this answer has been graded/resolved by teacher",
            ),
        ),
    ]
