# Generated by Django 5.2.6 on 2026-01-24 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumpost",
            name="parent_post",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent post if this is a reply",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="forum.forumpost",
            ),
        ),
    ]
