# Generated by Django 5.2.6 on 2026-01-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_forumpost_parent_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumthread",
            name="allow_replies",
            field=models.BooleanField(
                default=True, help_text="Whether students can reply to this thread"
            ),
        ),
    ]
