# Generated by Django 5.2.6 on 2026-02-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_postreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='forum_posts/'),
        ),
    ]
