# Generated by Django 5.2.6 on 2026-02-20 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_coursesection_quarter_scheduleslot_quarter'),
        ('forum', '0006_forumthread_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumthread',
            name='subject_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_threads', to='courses.subjectgroup'),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='type',
            field=models.CharField(choices=[('question', 'Question'), ('announcement', 'Announcement'), ('direct_message', 'Direct Message')], default='question', max_length=32),
        ),
    ]
