# Generated by Django (forum thread archived flag)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_forumpostattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='archived',
            field=models.BooleanField(
                default=False,
                help_text='Archived announcements are hidden from students',
            ),
        ),
    ]
