# Generated by Django 5.2.6 on 2025-09-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
