# Generated by Django 5.2.6 on 2025-09-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursesection_end_date_coursesection_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
