# Generated by Django 5.2.6 on 2025-12-22 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_coursesection_is_general_subjectgroup_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursesection",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Set for template sections that belong to a Course (not a specific SubjectGroup).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_sections",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="coursesection",
            name="template_section",
            field=models.ForeignKey(
                blank=True,
                help_text="Template section this section was derived from (if any).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_sections",
                to="courses.coursesection",
            ),
        ),
        migrations.AlterField(
            model_name="coursesection",
            name="subject_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Set for concrete sections of a specific SubjectGroup.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="courses.subjectgroup",
            ),
        ),
    ]
