# Generated by Django 5.2.6 on 2025-12-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0006_coursesection_course_coursesection_template_section_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="coursesection",
            name="template_duration_days",
            field=models.IntegerField(
                blank=True,
                help_text="Duration of the section in days (e.g. 7 for a week).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coursesection",
            name="template_start_offset_days",
            field=models.IntegerField(
                blank=True,
                help_text="Alternative to week index: offset in days from academic_start_date.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coursesection",
            name="template_week_index",
            field=models.IntegerField(
                blank=True,
                help_text="Week index in the academic year (0 = first week). Used to calculate start_date relative to academic_start_date.",
                null=True,
            ),
        ),
    ]
