# Generated by Django 5.2.6 on 2026-01-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_coursesection_template_duration_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="language",
            field=models.CharField(
                default="kazakh",
                help_text="Language of instruction (e.g., 'kazakh', 'russian', 'english')",
                max_length=50,
            ),
        ),
    ]
