# Generated by Django 5.2.6 on 2026-01-26 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_add_language_to_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Понедельник"),
                            (1, "Вторник"),
                            (2, "Среда"),
                            (3, "Четверг"),
                            (4, "Пятница"),
                            (5, "Суббота"),
                            (6, "Воскресенье"),
                        ],
                        help_text="Day of the week (0=Monday, 6=Sunday)",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        help_text="Start time of the lesson (e.g., 09:00)"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(help_text="End time of the lesson (e.g., 10:30)"),
                ),
                (
                    "room",
                    models.CharField(
                        blank=True,
                        help_text="Optional room/classroom number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional start date for this schedule slot",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional end date for this schedule slot",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_slots",
                        to="courses.subjectgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["day_of_week", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["subject_group", "day_of_week"],
                        name="courses_sch_subject_67d41b_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("subject_group", "day_of_week", "start_time"),
                        name="unique_slot_per_day_time",
                    )
                ],
            },
        ),
    ]
