# Generated by Django 5.2.6 on 2026-01-26 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_scheduleslot"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., '2024-2025 учебный год'", max_length=100
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Start of academic year (typically September 1)"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="End of academic year (typically May 25)"
                    ),
                ),
                ("quarter1_weeks", models.PositiveSmallIntegerField(default=8)),
                ("quarter2_weeks", models.PositiveSmallIntegerField(default=8)),
                ("quarter3_weeks", models.PositiveSmallIntegerField(default=10)),
                ("quarter4_weeks", models.PositiveSmallIntegerField(default=8)),
                (
                    "autumn_holiday_start",
                    models.DateField(
                        blank=True,
                        help_text="Autumn holiday start (default: Oct 27)",
                        null=True,
                    ),
                ),
                (
                    "autumn_holiday_end",
                    models.DateField(
                        blank=True,
                        help_text="Autumn holiday end (default: Nov 2)",
                        null=True,
                    ),
                ),
                (
                    "winter_holiday_start",
                    models.DateField(
                        blank=True,
                        help_text="Winter holiday start (default: Dec 29)",
                        null=True,
                    ),
                ),
                (
                    "winter_holiday_end",
                    models.DateField(
                        blank=True,
                        help_text="Winter holiday end (default: Jan 7)",
                        null=True,
                    ),
                ),
                (
                    "spring_holiday_start",
                    models.DateField(
                        blank=True,
                        help_text="Spring holiday start (default: Mar 19)",
                        null=True,
                    ),
                ),
                (
                    "spring_holiday_end",
                    models.DateField(
                        blank=True,
                        help_text="Spring holiday end (default: Mar 29)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the current active academic year",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Academic Year",
                "verbose_name_plural": "Academic Years",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Holiday name (e.g., 'День Независимости')",
                        max_length=100,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False,
                        help_text="If true, this holiday repeats every year",
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        help_text="If null, applies to all academic years",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_holidays",
                        to="courses.academicyear",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
    ]
