# Generated by Django 5.2.6 on 2026-01-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_academicyear_holiday"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursesection",
            name="quarter",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "1 четверть"),
                    (2, "2 четверть"),
                    (3, "3 четверть"),
                    (4, "4 четверть"),
                ],
                help_text="Quarter this section belongs to (null = all quarters or general section)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="scheduleslot",
            name="quarter",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "1 четверть"),
                    (2, "2 четверть"),
                    (3, "3 четверть"),
                    (4, "4 четверть"),
                ],
                help_text="Quarter this schedule applies to (null = all quarters)",
                null=True,
            ),
        ),
    ]
