# Generated by Django 5.2.6 on 2026-03-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_coursesection_quarter_scheduleslot_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectgroup',
            name='color',
            field=models.CharField(blank=True, help_text='Custom hex color, e.g. #FF5733', max_length=7, null=True),
        ),
    ]
