# Generated by Django 5.2.6 on 2026-03-04 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_subjectgroup_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_index', models.PositiveSmallIntegerField(choices=[(1, '1 четверть'), (2, '2 четверть'), (3, '3 четверть'), (4, '4 четверть')], help_text='Quarter index (1 to 4)')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='courses.academicyear')),
            ],
            options={
                'verbose_name': 'Quarter',
                'verbose_name_plural': 'Quarters',
                'ordering': ['academic_year', 'quarter_index'],
                'unique_together': {('academic_year', 'quarter_index')},
            },
        ),
    ]
