# Generated by Django
from django.db import migrations
from datetime import timedelta

def populate_quarters(apps, schema_editor):
    AcademicYear = apps.get_model('courses', 'AcademicYear')
    Quarter = apps.get_model('courses', 'Quarter')
    
    for year in AcademicYear.objects.all():
        weeks_per_quarter = [
            year.quarter1_weeks,
            year.quarter2_weeks,
            year.quarter3_weeks,
            year.quarter4_weeks,
        ]
        
        current_date = year.start_date
        for q in range(1, 5):
            quarter_start = current_date
            quarter_weeks = weeks_per_quarter[q - 1]
            
            days_to_add = quarter_weeks * 7
            quarter_end = current_date + timedelta(days=days_to_add - 1)
            
            # Adjust for holidays in Q1
            if q == 1 and year.autumn_holiday_start and year.autumn_holiday_end:
                if year.autumn_holiday_start <= quarter_end:
                    days_to_add += (year.autumn_holiday_end - year.autumn_holiday_start).days + 1
            
            quarter_end = current_date + timedelta(days=days_to_add - 1)
            
            Quarter.objects.create(
                academic_year=year,
                quarter_index=q,
                start_date=quarter_start,
                end_date=quarter_end
            )
            
            current_date = quarter_end + timedelta(days=1)

def reverse_quarters(apps, schema_editor):
    Quarter = apps.get_model('courses', 'Quarter')
    Quarter.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_add_quarter_model'),
    ]

    operations = [
        migrations.RunPython(populate_quarters, reverse_quarters),
    ]
