# Generated by Django 5.2.6 on 2026-03-04 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_populate_quarters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='quarter1_weeks',
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='quarter2_weeks',
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='quarter3_weeks',
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='quarter4_weeks',
        ),
    ]
