# Generated by Django 5.2.6 on 2026-03-04 09:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_quarter_weeks'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AcademicPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=255)),
                ('academic_year', models.CharField(help_text="e.g., '2025-2026'", max_length=100)),
                ('school_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_plans', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='PlanQuarterDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sor_count', models.PositiveIntegerField(default=0)),
                ('soch_count', models.PositiveIntegerField(default=0)),
                ('total_hours', models.PositiveIntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarter_details', to='courses.academicplan')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_details', to='courses.quarter')),
            ],
            options={
                'unique_together': {('plan', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('plan_quarter_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.planquarterdetail')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.PositiveIntegerField()),
                ('topic', models.CharField(max_length=255)),
                ('hours', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('objectives', models.ManyToManyField(blank=True, related_name='lessons', to='courses.learningobjective')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.section')),
            ],
            options={
                'ordering': ['lesson_number'],
            },
        ),
        migrations.CreateModel(
            name='PlanSubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_subject_groups', to='courses.academicplan')),
                ('subject_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ktp_links', to='courses.subjectgroup')),
            ],
            options={
                'unique_together': {('plan', 'subject_group')},
            },
        ),
    ]
