# Generated by Django 5.2.6 on 2026-03-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_learningobjective_academicplan_planquarterdetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_summative',
            field=models.BooleanField(default=False, help_text='True if this lesson is a SOR or SOCH'),
        ),
    ]
