# Generated by Django 5.2.6 on 2025-09-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_assignment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='file_url',
        ),
        migrations.AddField(
            model_name='assignmentattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignment_attachments/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
        migrations.AddField(
            model_name='submissionattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submission_attachments/'),
        ),
    ]
