# Generated by Django 5.2.6 on 2025-09-20 10:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_initial'),
        ('learning', '0005_remove_submission_file_url_assignmentattachment_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the attendance session', null=True)),
                ('subject_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='courses.subjectgroup')),
                ('taken_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('excused', 'Excused'), ('not_present', 'Not Present')], default='not_present', max_length=20)),
                ('notes', models.TextField(blank=True, help_text="Optional notes about this student's attendance", null=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='learning.attendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['subject_group', 'taken_at'], name='learning_at_subject_798a80_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['taken_by', 'taken_at'], name='learning_at_taken_b_1fbcc7_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student'], name='learning_at_student_f0582f_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['status'], name='learning_at_status_4dacfd_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('attendance', 'student'), name='unique_attendance_student'),
        ),
    ]
