# Generated by Django 5.2.6 on 2025-09-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_attendance_attendancerecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('file', 'File'), ('link', 'Link'), ('directory', 'Directory'), ('text', 'Text'), ('video', 'Video'), ('audio', 'Audio'), ('image', 'Image'), ('pdf', 'PDF'), ('word', 'Word'), ('excel', 'Excel'), ('powerpoint', 'Powerpoint')], max_length=32),
        ),
    ]
