# Generated by Django 5.2.6 on 2025-09-26 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursesection_end_date_coursesection_start_date'),
        ('learning', '0007_alter_resource_type'),
        ('schools', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('lesson', 'Lesson'), ('school_event', 'School Event'), ('other', 'Other')], default='other', max_length=32)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='courses.coursesection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='schools.school')),
                ('subject_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='courses.subjectgroup')),
            ],
            options={
                'ordering': ['start_at', 'id'],
                'indexes': [models.Index(fields=['type', 'start_at'], name='learning_ev_type_52bb7b_idx'), models.Index(fields=['school', 'start_at'], name='learning_ev_school__f4fc67_idx'), models.Index(fields=['subject_group', 'start_at'], name='learning_ev_subject_ebaf83_idx'), models.Index(fields=['course_section', 'start_at'], name='learning_ev_course__3b5123_idx')],
            },
        ),
    ]
