# Generated by Django 5.2.6 on 2025-09-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('file', 'File'), ('link', 'Link'), ('directory', 'Directory'), ('text', 'Text'), ('video', 'Video'), ('audio', 'Audio'), ('image', 'Image'), ('pdf', 'PDF'), ('word', 'Word'), ('excel', 'Excel'), ('powerpoint', 'Powerpoint'), ('lesson_link', 'Lesson Link')], max_length=32),
        ),
    ]
