# Generated by Django 5.2.6 on 2025-12-22 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0009_alter_resource_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="is_unlinked_from_template",
            field=models.BooleanField(
                default=False,
                help_text="If true, this assignment is no longer auto-synced from its template.",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="template_assignment",
            field=models.ForeignKey(
                blank=True,
                help_text="Template assignment this assignment was cloned from (if any).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_assignments",
                to="learning.assignment",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="is_unlinked_from_template",
            field=models.BooleanField(
                default=False,
                help_text="If true, this resource is no longer auto-synced from its template.",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="template_resource",
            field=models.ForeignKey(
                blank=True,
                help_text="Template resource this resource was cloned from (if any).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_resources",
                to="learning.resource",
            ),
        ),
    ]
