# Generated by Django 5.2.6 on 2025-12-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0010_assignment_is_unlinked_from_template_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="template_due_time",
            field=models.TimeField(
                blank=True,
                help_text="Time of day for assignment due datetime (for templates).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="template_offset_days_from_section_start",
            field=models.IntegerField(
                blank=True,
                help_text="Offset in days from section start date to assignment due date (for templates).",
                null=True,
            ),
        ),
    ]
