# Generated by Django 5.2.6 on 2026-02-01 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_coursesection_quarter_scheduleslot_quarter"),
        ("learning", "0011_assignment_template_due_time_and_more"),
        ("schools", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="target_audience",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("teachers", "Teachers"),
                    ("class", "Class"),
                    ("specific", "Specific"),
                ],
                default="all",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="target_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Для target_audience=specific: кому показывать событие.",
                related_name="targeted_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("lesson", "Lesson"),
                    ("school_event", "School Event"),
                    ("meeting", "Meeting"),
                    ("gathering", "Gathering"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["target_audience", "start_at"],
                name="learning_ev_target__40f5b9_idx",
            ),
        ),
    ]
