# Generated by Django 5.2.6 on 2026-02-02 06:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_coursesection_quarter_scheduleslot_quarter"),
        ("learning", "0012_event_target_audience_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.PositiveIntegerField(help_text="Балл (например 5 или 85)."),
                ),
                (
                    "max_value",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Максимум баллов (5 для 5-балльной шкалы, 100 для 100-балльной).",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Краткое название (например «Контрольная №2», «Ответ на уроке»).",
                        max_length=255,
                    ),
                ),
                (
                    "grade_type",
                    models.CharField(
                        choices=[
                            ("lesson", "На уроке"),
                            ("offline_test", "Контрольная работа (оффлайн)"),
                            ("oral", "Устный ответ"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("graded_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("feedback", models.TextField(blank=True, null=True)),
                (
                    "course_section",
                    models.ForeignKey(
                        blank=True,
                        help_text="Тема/раздел (опционально).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manual_grades",
                        to="courses.coursesection",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_manual_grades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_grades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_grades",
                        to="courses.subjectgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-graded_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["student", "subject_group"],
                        name="learning_ma_student_a379c2_idx",
                    ),
                    models.Index(
                        fields=["subject_group", "graded_at"],
                        name="learning_ma_subject_6957db_idx",
                    ),
                ],
            },
        ),
    ]
