# Generated by Django 5.2.6 on 2026-02-02 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_coursesection_quarter_scheduleslot_quarter"),
        ("learning", "0013_add_manual_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("assignment", "Задание"),
                            ("test", "Тест"),
                            ("manual", "Ручная оценка"),
                        ],
                        help_text="Тип оценки: задание, тест или ручная.",
                        max_length=32,
                    ),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Вес (целое число, обычно 1–3). По умолчанию 1.",
                    ),
                ),
                (
                    "subject_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_weights",
                        to="courses.subjectgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["subject_group", "source_type"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("subject_group", "source_type"),
                        name="unique_subject_group_source_type",
                    )
                ],
            },
        ),
    ]
