# Generated by Django 5.2.6 on 2026-02-02 07:43

import django.core.validators
from django.db import migrations, models


def set_weights_sum_100(apps, schema_editor):
    GradeWeight = apps.get_model("learning", "GradeWeight")
    for sg_id in GradeWeight.objects.values_list("subject_group_id", flat=True).distinct():
        rows = list(GradeWeight.objects.filter(subject_group_id=sg_id).order_by("source_type"))
        if not rows:
            continue
        # Распределить 100%: 34, 33, 33 или поровну для 1–2 строк
        n = len(rows)
        if n == 3:
            vals = [34, 33, 33]
        elif n == 2:
            vals = [50, 50]
        else:
            vals = [100]
        for i, row in enumerate(rows):
            row.weight = vals[i]
            row.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0014_add_grade_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradeweight",
            name="weight",
            field=models.PositiveSmallIntegerField(
                default=34,
                help_text="Вес в процентах (0–100). Сумма по трём типам = 100%.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.RunPython(set_weights_sum_100, noop),
    ]
