# Generated by Django 5.2.6 on 2026-02-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0015_grade_weight_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_visible_to_students',
            field=models.BooleanField(default=True, help_text='If false, this resource is visible only to teachers, school admins, and super admins.'),
        ),
    ]
