# Generated by Django 5.2.6 on 2026-03-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0017_resource_week_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeweight',
            name='source_type',
            field=models.CharField(choices=[('assignment', 'Задание'), ('test', 'Тест'), ('manual', 'Формативное оценивание (ФО)')], help_text='Тип оценки: задание, тест или ФО.', max_length=32),
        ),
    ]
