# Generated by Django 5.2.6 on 2026-03-11 13:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_lesson_is_summative'),
        ('learning', '0018_alter_gradeweight_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualgrade',
            name='weight_in_category',
            field=models.PositiveSmallIntegerField(default=100, help_text='Вес этой оценки внутри категории (в процентах)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='GradeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории (например: ФО, Экзамен 1)', max_length=255)),
                ('weight', models.PositiveSmallIntegerField(default=0, help_text='Вес категории в процентах от итоговой оценки', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_formative', models.BooleanField(default=False, help_text='Является ли эта категория Формативным оцениванием (ФО)')),
                ('subject_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_categories', to='courses.subjectgroup')),
            ],
            options={
                'ordering': ['subject_group', '-is_formative', 'name'],
            },
        ),
        migrations.AddField(
            model_name='manualgrade',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Категория оценки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_grades', to='learning.gradecategory'),
        ),
        migrations.DeleteModel(
            name='GradeWeight',
        ),
        migrations.AddConstraint(
            model_name='gradecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_formative', True)), fields=('subject_group',), name='unique_formative_category_per_group'),
        ),
    ]
