# Generated by Django 5.1 on 2025-09-17 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField()),
                ('letter', models.CharField(max_length=1)),
                ('language', models.CharField(max_length=50)),
                ('kundelik_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(default='Kazakhstan', max_length=255)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=64, null=True)),
                ('kundelik_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_users', to='schools.classroom')),
            ],
        ),
    ]
