# Generated by Django 5.1 on 2025-09-17 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='schools.school'),
        ),
        migrations.AddConstraint(
            model_name='classroomuser',
            constraint=models.UniqueConstraint(fields=('classroom', 'user'), name='_class_user_uc'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.CheckConstraint(condition=models.Q(('grade__gte', 0), ('grade__lte', 12)), name='check_grade_range'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('school', 'grade', 'letter'), name='uq_classroom_per_school'),
        ),
    ]
